# Generated by Django 5.2 on 2025-05-27 13:04

import CF.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PublicCible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Numéro de la région', unique=True)),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Région',
                'verbose_name_plural': 'Régions',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CentreFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=100, unique=True)),
                ('sigle', models.CharField(blank=True, max_length=20)),
                ('adresse', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('capacite_max', models.PositiveIntegerField(default=0, help_text="Capacité d'accueil maximale")),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centres', to='CF.commune')),
                ('public_cibles', models.ManyToManyField(blank=True, related_name='centres', to='CF.publiccible')),
                ('secteurs', models.ManyToManyField(related_name='centres', to='CF.secteur')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentAdministratif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrat_bail', models.FileField(blank=True, null=True, upload_to=CF.models.document_upload_path)),
                ('titre_foncier', models.FileField(blank=True, null=True, upload_to=CF.models.document_upload_path)),
                ('autre_document', models.FileField(blank=True, null=True, upload_to=CF.models.document_upload_path)),
                ('immatriculation_cnss', models.FileField(blank=True, null=True, upload_to=CF.models.document_upload_path)),
                ('immatriculation_acfpe', models.FileField(blank=True, null=True, upload_to=CF.models.document_upload_path)),
                ('acquittement_fiscal', models.FileField(blank=True, null=True, upload_to=CF.models.document_upload_path)),
                ('agrement_valide', models.FileField(blank=True, null=True, upload_to=CF.models.document_upload_path)),
                ('centre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_administratif', to='CF.centreformation')),
            ],
        ),
        migrations.CreateModel(
            name='PersonneReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('fonction_libre', models.CharField(help_text='Ex : directeur, tuteur, etc.', max_length=50)),
                ('centre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personne_reference', to='CF.centreformation')),
            ],
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefectures', to='CF.region')),
            ],
            options={
                'unique_together': {('nom', 'region')},
            },
        ),
        migrations.CreateModel(
            name='SousPrefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_prefectures', to='CF.prefecture')),
            ],
            options={
                'unique_together': {('nom', 'prefecture')},
            },
        ),
        migrations.AddField(
            model_name='commune',
            name='sous_prefecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='CF.sousprefecture'),
        ),
        migrations.AlterUniqueTogether(
            name='commune',
            unique_together={('nom', 'sous_prefecture')},
        ),
    ]
