# Generated by Django 5.2 on 2025-07-06 06:41

import CF.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PublicCible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Numéro de la région', unique=True)),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Région',
                'verbose_name_plural': 'Régions',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CentreFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=100, unique=True)),
                ('sigle', models.CharField(blank=True, max_length=20)),
                ('categorie', models.CharField(blank=True, choices=[('1e', '1ère catégorie'), ('2e', '2ème catégorie'), ('3e', '3ème catégorie')], max_length=2, verbose_name='Catégorie')),
                ('adresse', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centres', to='CF.commune')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentAdministratif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrat_bail', models.FileField(blank=True, null=True, upload_to=CF.models.document_upload_path)),
                ('titre_foncier', models.FileField(blank=True, null=True, upload_to=CF.models.document_upload_path)),
                ('autre_document', models.FileField(blank=True, null=True, upload_to=CF.models.document_upload_path)),
                ('immatriculation_cnss', models.FileField(blank=True, null=True, upload_to=CF.models.document_upload_path)),
                ('immatriculation_acfpe', models.FileField(blank=True, null=True, upload_to=CF.models.document_upload_path)),
                ('acquittement_fiscal', models.FileField(blank=True, null=True, upload_to=CF.models.document_upload_path)),
                ('agrement_valide', models.FileField(blank=True, null=True, upload_to=CF.models.document_upload_path)),
                ('centre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_administratif', to='CF.centreformation')),
            ],
        ),
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_formateur_permanant', models.PositiveIntegerField(default=0)),
                ('nombre_formateur_nonpermanant', models.PositiveIntegerField(default=0)),
                ('niveaux_formateur', models.JSONField(blank=True, default=list)),
                ('annees_experience_formateur', models.JSONField(blank=True, default=list)),
                ('centre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formateur', to='CF.centreformation')),
            ],
        ),
        migrations.CreateModel(
            name='PersonneReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('fonction_libre', models.CharField(help_text='Ex : directeur, tuteur, etc.', max_length=50)),
                ('centre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personne_reference', to='CF.centreformation')),
            ],
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefectures', to='CF.region')),
            ],
            options={
                'unique_together': {('nom', 'region')},
            },
        ),
        migrations.CreateModel(
            name='DomaineActiviteCapacite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_experience', models.PositiveIntegerField(default=0)),
                ('liste_activites', models.TextField(blank=True, help_text='Liste des activités proposées (ex: couture, menuiserie, informatique...)')),
                ('activites_populaires', models.TextField(blank=True, help_text='Activités les plus pratiquées ou demandées')),
                ('capacite_max', models.PositiveIntegerField(default=0, help_text='Nombre de personnes pouvant être accueillies par jour')),
                ('nombre_salles', models.PositiveIntegerField(default=0, help_text='Nombre total de salles disponibles')),
                ('ListeAtelier', models.TextField(blank=True, help_text='Listes des ateliers et lieu de formation')),
                ('centre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='domaine_activité_capacité', to='CF.centreformation')),
                ('public_cibles', models.ManyToManyField(blank=True, related_name='centres', to='CF.publiccible')),
                ('secteurs', models.ManyToManyField(related_name='centres', to='CF.secteur')),
            ],
        ),
        migrations.CreateModel(
            name='SousPrefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sousprefectures', to='CF.prefecture')),
            ],
            options={
                'unique_together': {('nom', 'prefecture')},
            },
        ),
        migrations.AddField(
            model_name='commune',
            name='sous_prefecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='CF.sousprefecture'),
        ),
        migrations.AlterUniqueTogether(
            name='commune',
            unique_together={('nom', 'sous_prefecture')},
        ),
    ]
