# Generated by Django 5.2 on 2025-05-08 08:06

import CF.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PublicCible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CentreFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=200)),
                ('sigle', models.CharField(blank=True, max_length=50)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('bp', models.CharField(blank=True, max_length=50)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CF.commune')),
                ('public_cibles', models.ManyToManyField(blank=True, related_name='centres', to='CF.publiccible')),
                ('secteurs', models.ManyToManyField(related_name='centres', to='CF.secteur')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentAdministratif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrat_bail', models.FileField(blank=True, null=True, upload_to=CF.models.document_upload_path)),
                ('titre_foncier', models.FileField(blank=True, null=True, upload_to=CF.models.document_upload_path)),
                ('autre_document', models.FileField(blank=True, null=True, upload_to=CF.models.document_upload_path)),
                ('immatriculation_cnss', models.FileField(blank=True, null=True, upload_to=CF.models.document_upload_path)),
                ('immatriculation_acfpe', models.FileField(blank=True, null=True, upload_to=CF.models.document_upload_path)),
                ('acquittement_fiscal', models.FileField(blank=True, null=True, upload_to=CF.models.document_upload_path)),
                ('agrement_valide', models.FileField(blank=True, null=True, upload_to=CF.models.document_upload_path)),
                ('centre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CF.centreformation')),
            ],
        ),
        migrations.CreateModel(
            name='PersonneReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fonction_libre', models.CharField(help_text='Ex: contact principal, tuteur, etc.', max_length=100)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CF.centreformation')),
            ],
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CF.region')),
            ],
        ),
        migrations.CreateModel(
            name='SousPrefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CF.prefecture')),
            ],
        ),
        migrations.AddField(
            model_name='commune',
            name='sous_prefecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CF.sousprefecture'),
        ),
    ]
