# Generated by Django 5.2 on 2025-05-30 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CF', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefecture',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CF.region'),
        ),
        migrations.AlterField(
            model_name='sousprefecture',
            name='prefecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sousprefectures', to='CF.prefecture'),
        ),
    ]
