# Generated by Django 5.2 on 2025-05-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CF', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centreformation',
            name='adresse',
            field=models.CharField(max_length=30),
        ),
    ]
