# Generated by Django 5.2 on 2025-06-04 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CF', '0002_alter_prefecture_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centreformation',
            name='activites_populaires',
            field=models.TextField(blank=True, help_text='Activités les plus pratiquées ou demandées'),
        ),
        migrations.AddField(
            model_name='centreformation',
            name='liste_activites',
            field=models.TextField(blank=True, help_text='Liste des activités proposées (ex: couture, menuiserie, informatique...)'),
        ),
        migrations.AlterField(
            model_name='prefecture',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefectures', to='CF.region'),
        ),
    ]
