# Generated by Django 5.2 on 2025-05-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CF', '0002_alter_centreformation_adresse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centreformation',
            name='bp',
        ),
        migrations.AddField(
            model_name='centreformation',
            name='capacite_max',
            field=models.IntegerField(default=0, help_text="Capacité d'accueil maximale du centre"),
        ),
    ]
